nelmio_cors:
    defaults:
            allow_credentials: false
            allow_origin: [https://localhost:8000/]
            allow_headers: []
            allow_methods: ['GET']
            expose_headers: []
            max_age: 0
            hosts: []
            origin_regex: false
    paths:
        '^/':
            allow_origin: [https://localhost:8000/]
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600
        '^/lists':
            allow_origin: [https://localhost:8000/]
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600
        'http://localhost:8000/lists':
            allow_origin: [https://localhost:8000/]
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600
        'https://localhost:8000/lists':
            allow_origin: [https://localhost:8000/]
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600
